/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.retrozinndev.jsonutils;

import java.io.File;

import com.retrozinndev.jsonutils.Message.Type;

public class JSON {
    protected File json;

    /**
     * Creates a new JSON instance for the desired JSON file.
     * @param jsonDir
     * The desired json file directory.
     */
    public JSON(String jsonDir) {
        json = new File(jsonDir);
        checkIfExists(json);
    }

    /**
     * Creates a new JSON instance for the desired JSON file.
     * @param jsonFile
     * The desired json file.
     */
    public JSON(File jsonFile) {
        json = jsonFile;
        checkIfExists(json);
    }

    /**
     * Gets the value of a key in a JSON.
     * @param keyString
     * The key used to return it's value.
     * @return
     * The value of the key in the JSON.
    */
    public String getValue(String keyString) {
        return ""; //TODO
    }

    /**
     * Checks if a file exists.
     * @param file
     * The file to check existance.
     * @return
     * Boolean that confirms if the file exists or not.
     */
    private final boolean checkIfExists(File file) {
        if(file.exists()) 
            return file.exists();

        Message.send(Type.Error, "JSON not found in dir \""+file.toString()+"\".");
        return false;
    }



}
